/**
 * Mock featured jobs data
 * Used as fallback when API is not available or returns empty results
 */

import type { Job } from '@/src/types/jobs';

export const MOCK_FEATURED_JOBS: Job[] = [
  {
    id: '1',
    title: 'Senior Frontend Engineer',
    company: 'TechCorp',
    company_logo: 'T',
    company_color_class: 'bg-blue-500',
    location: 'Bangalore, India',
    work_mode: 'onsite',
    job_type: 'full-time',
    experience_min: 3,
    experience_max: 5,
    salary_min: 1200000,
    salary_max: 1800000,
    salary_lpa_min: '12',
    salary_lpa_max: '18',
    skills: ['React', 'TypeScript', 'Next.js'],
    company_type: 'product',
    is_new: true,
    is_hot: false,
    applicants: 45,
    posted_at: new Date().toISOString(),
  },
  {
    id: '2',
    title: 'Backend Developer (Python)',
    company: 'DataSystems',
    company_logo: 'D',
    company_color_class: 'bg-purple-500',
    location: 'Hyderabad, India',
    work_mode: 'hybrid',
    job_type: 'full-time',
    experience_min: 2,
    experience_max: 4,
    salary_min: 1000000,
    salary_max: 1500000,
    salary_lpa_min: '10',
    salary_lpa_max: '15',
    skills: ['Python', 'FastAPI', 'PostgreSQL'],
    company_type: 'product',
    is_new: false,
    is_hot: true,
    applicants: 32,
    posted_at: new Date().toISOString(),
  },
  {
    id: '3',
    title: 'Full Stack Developer',
    company: 'WebSolutions',
    company_logo: 'W',
    company_color_class: 'bg-green-500',
    location: 'Mumbai, India',
    work_mode: 'remote',
    job_type: 'full-time',
    experience_min: 2,
    experience_max: 4,
    salary_min: 1100000,
    salary_max: 1600000,
    salary_lpa_min: '11',
    salary_lpa_max: '16',
    skills: ['JavaScript', 'React', 'Node.js', 'MongoDB'],
    company_type: 'startup',
    is_new: true,
    is_hot: false,
    applicants: 58,
    posted_at: new Date().toISOString(),
  },
  {
    id: '4',
    title: 'DevOps Engineer',
    company: 'CloudOps',
    company_logo: 'C',
    company_color_class: 'bg-orange-500',
    location: 'Pune, India',
    work_mode: 'hybrid',
    job_type: 'full-time',
    experience_min: 3,
    experience_max: 6,
    salary_min: 1300000,
    salary_max: 2000000,
    salary_lpa_min: '13',
    salary_lpa_max: '20',
    skills: ['Kubernetes', 'Docker', 'AWS', 'Terraform'],
    company_type: 'service',
    is_new: false,
    is_hot: true,
    applicants: 27,
    posted_at: new Date().toISOString(),
  },
  {
    id: '5',
    title: 'QA Engineer (Automation)',
    company: 'QualityFirst',
    company_logo: 'Q',
    company_color_class: 'bg-pink-500',
    location: 'Chennai, India',
    work_mode: 'onsite',
    job_type: 'full-time',
    experience_min: 2,
    experience_max: 4,
    salary_min: 800000,
    salary_max: 1200000,
    salary_lpa_min: '8',
    salary_lpa_max: '12',
    skills: ['Selenium', 'Python', 'Jest', 'CI/CD'],
    company_type: 'service',
    is_new: true,
    is_hot: false,
    applicants: 19,
    posted_at: new Date().toISOString(),
  },
];
